## k近邻
### 0.引入依赖

In [5]:
import numpy as np
import pandas as pd


from sklearn.datasets import load_iris # 引入sklearn中的数据集 iris 使用iris....
from sklearn.model_selection import train_test_split # 划分训练集和测试集
from sklearn.metrics import accuracy_score # 分类预测的准确率

### 1.数据加载和预处理

In [6]:
iris = load_iris()
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['class'] = iris.target # 加上'class'这一列 并赋值
df['class'] = df['class'].map({0:iris.target_names[0], 1:iris.target_names[1], 2:iris.target_names[2]})
df.describe() # descriptive statistics

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [7]:
X = iris.data
y = iris.target
# y = iris.target.reshape(-1, 1)    # -1：不管有多少行，排成一个任意行，一列的矩阵

# 划分训练集和测试集
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=35, stratify=y)
# stratify 按照y的分布等比例分割 出来两个集



# 
# X_test[0].shape
# new_X = X_test[0].reshape(1,4)
# np.abs(X_train-new_X)
# # np.abs(X_train-X_test[0])

### 2.核心算法实现

In [8]:
# 距离函数定义


# 曼哈顿距离
def l1_distance(a, b):
    return np.sum( np.abs(a-b),axis=1)

# 欧式距离
def l2_distance(a, b):
    return np.sqrt( np.sum((a-b)**2, axis=1) )

# 分类器实现
class kNN(object):
    
    # 定义一个初始化方法 __init__ 类的构造方法
    def __init__(self, n_neighbors = 1, dist_func = l1_distance):
        self.n_neighbors = n_neighbors
        self.dist_func = dist_func
        
    # 训练模型方法
    def fit(self, x, y):
        self.X_train = x
        self.y_train = y

    # 模型预测方法
    def predict(self, X):
        # 初始化预测分类
        y_pred = np.zeros((X.shape[0],1), dtype=self.y_train.dtype)
        
        # X 传入可能是多组特征向量，对于就有多组的分类结果, 需要遍历来预测
        for i, X_test in enumerate(X):
            # X_test与所有训练数据计算数据
            dists = self.dist_func(self.X_train, X_test)
            # 按照从近到远排序
            nn_index = np.argsort(dists) # nn_index为原来的位置
            # 选择最近的k个点，这里nn_y是最近的k个点的类别。如[1,0,0,2,2,2]这样
            # 0,1,2分布代表一个类别
            nn_y = self.y_train[ nn_index[ :self.n_neighbors] ]
            # 统计出现次数最多的那个类别
# np.bincount(x) 统计并返回返回下标出现的次数，长度为x中的最大值0-max(x)。这里下标为类别
# np.argmax(x) 返回x中最大值对应的下标，这里下标就是类别 
            y_pred[i] = np.argmax( np.bincount(nn_y) ) # 第i组的特征向量预测得到的类别
            
        return y_pred

### 3.测试

In [9]:
knn = kNN(n_neighbors=3)
knn.fit(X_train, y_train)


y_pred = knn.predict(X_test)
score = accuracy_score(y_test, y_pred)
print(score)

0.9333333333333333


In [41]:
 b = np.array([
     (4,5,6,9),
     (3,4,4,8),
     (1,3,2,7)
     
 ])
b.sort(axis=0)
b
# ravel 展开成一维数组

array([[1, 3, 2, 7],
       [3, 4, 4, 8],
       [4, 5, 6, 9]])

In [1]:
import numpy as np

In [46]:
a= np.array( [9,8,7,6,5,4,3,2,1])
a[:3]

array([9, 8, 7])

In [49]:
a = np.array( [0,0,0,0,0,2,2,100])
np.bincount(a)  # 下标idx 对应的值 代表 idx出现的次数   长度为 输入数组的最大值

array([5, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int64)